import dotenv from 'dotenv';
import { createClient } from '@supabase/supabase-js';

dotenv.config();
//supabase setup
const supabase = createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_KEY
);

/**
 * Array of skill categories with specific skills listed.
 * 
 * @constant {Array<Object>} Skills - List of skills categorized under different domains.
 * @property {string} Skills[].Skills - The name of the skill.
 */
const Skills = [
    // Existing Design & Visual Arts Skills
    { "Skills": "Logo Design" },
    { "Skills": "Stationery Design" },
    { "Skills": "Fonts & Typography" },
    { "Skills": "Branding Services" },
    { "Skills": "Book Design" },
    { "Skills": "Packaging Design" },
    { "Skills": "Album Cover Design" },
    { "Skills": "Signage Design" },
    { "Skills": "Invitation Design" },
    { "Skills": "T-Shirt & Merchandise" },
    { "Skills": "Flyer & Brochure Design" },
    { "Skills": "Poster Design" },
    { "Skills": "Identity Design" },
    { "Skills": "Brand Guidelines" },
    { "Skills": "Website Design" },
    { "Skills": "App Design" },
    { "Skills": "UI/UX Design" },
    { "Skills": "Landing Page Design" },
    { "Skills": "Icon Design" },
    { "Skills": "Illustrations" },
    { "Skills": "Portraits" },
    { "Skills": "Comics & Character Design" },
    { "Skills": "Fashion Design" },
    { "Skills": "Pattern Design" },
    { "Skills": "Storyboards" },
    { "Skills": "Tattoo Design" },
    { "Skills": "NFT Art" },
    { "Skills": "3D Illustration" },
    { "Skills": "Children's Illustration" },
    { "Skills": "Social Media Design" },
    { "Skills": "Presentation Design" },
    { "Skills": "Infographic Design" },
    { "Skills": "Resume Design" },
    { "Skills": "Copywriting" },
    { "Skills": "Product Photography" },
    { "Skills": "Landscape Photography" },
    { "Skills": "Image Editing & Retouching" },
    { "Skills": "Portrait Photography" },
    { "Skills": "Architecture & Interior Design" },
    { "Skills": "Landscape Design" },
    { "Skills": "Industrial Design" },
    { "Skills": "Graphics for Streamers" },
    { "Skills": "Game Design" },
    { "Skills": "Creative Tool Coaching" },
    { "Skills": "Mentorship & Career Advice" },
    { "Skills": "Modeling Projects" },
    { "Skills": "Architecture Renderings" },
    { "Skills": "Music Composition & Production" },
    { "Skills": "Sound Design" },
    { "Skills": "Animated Gifs" },
    { "Skills": "Logo Animation" },
    { "Skills": "Motion Graphics" },
    { "Skills": "Video Production & Editing" },
    { "Skills": "Explainer Videos" },
    { "Skills": "Short Video Ads" },
    
    // Additional Creative Industry Skills
    { "Skills": "Art Direction" },
    { "Skills": "Exhibition Design" },
    { "Skills": "Environmental Design" },
    { "Skills": "Mural Design" },
    { "Skills": "Concept Art" },
    { "Skills": "Character Animation" },
    { "Skills": "Stop Motion Animation" },
    { "Skills": "3D Modeling" },
    { "Skills": "3D Animation" },
    { "Skills": "Virtual Reality Design" },
    { "Skills": "Augmented Reality Design" },
    { "Skills": "Textile Design" },
    { "Skills": "Jewelry Design" },
    { "Skills": "Furniture Design" },
    { "Skills": "Product Design" },
    { "Skills": "Sustainable Design" },
    { "Skills": "Print Production" },
    { "Skills": "Digital Fabrication" },
    { "Skills": "Set Design" },
    { "Skills": "Costume Design" },
    { "Skills": "Makeup Artistry" },
    { "Skills": "Special Effects" },
    { "Skills": "Color Grading" },
    { "Skills": "Cinematography" },
    { "Skills": "Drone Photography" },
    { "Skills": "Food Photography" },
    { "Skills": "Street Photography" },
    { "Skills": "Fashion Photography" },
    { "Skills": "Event Photography" },
    { "Skills": "Calligraphy" },
    { "Skills": "Hand Lettering" },
    { "Skills": "Printmaking" },
    { "Skills": "Sculpture" },
    { "Skills": "Painting" },
    { "Skills": "Drawing" },
    { "Skills": "Collage" },
    { "Skills": "Mixed Media" },
    { "Skills": "Fine Art" },
    { "Skills": "Content Strategy" },
    { "Skills": "Editorial Design" },
    { "Skills": "Email Design" },
    { "Skills": "Marketing Design" },
    
    // General Professional Skills
    { "Skills": "Project Management" },
    { "Skills": "Team Leadership" },
    { "Skills": "Client Relations" },
    { "Skills": "Strategic Planning" },
    { "Skills": "Budget Management" },
    { "Skills": "Time Management" },
    { "Skills": "Communication" },
    { "Skills": "Presentation Skills" },
    { "Skills": "Negotiation" },
    { "Skills": "Problem Solving" },
    { "Skills": "Critical Thinking" },
    { "Skills": "Creativity" },
    { "Skills": "Collaboration" },
    { "Skills": "Marketing Strategy" },
    { "Skills": "Market Research" },
    { "Skills": "Data Analysis" },
    { "Skills": "SEO/SEM" },
    { "Skills": "Social Media Management" },
    { "Skills": "Content Marketing" },
    { "Skills": "Email Marketing" },
    { "Skills": "Influencer Marketing" },
    { "Skills": "Public Relations" },
    { "Skills": "Brand Strategy" },
    { "Skills": "Customer Experience" },
    
    // Technical Skills
    { "Skills": "HTML/CSS" },
    { "Skills": "JavaScript" },
    { "Skills": "React" },
    { "Skills": "Vue.js" },
    { "Skills": "Angular" },
    { "Skills": "WordPress" },
    { "Skills": "Shopify" },
    { "Skills": "Webflow" },
    { "Skills": "Figma" },
    { "Skills": "Adobe Creative Suite" },
    { "Skills": "Adobe Photoshop" },
    { "Skills": "Adobe Illustrator" },
    { "Skills": "Adobe InDesign" },
    { "Skills": "Adobe XD" },
    { "Skills": "Adobe After Effects" },
    { "Skills": "Adobe Premiere Pro" },
    { "Skills": "Sketch" },
    { "Skills": "Blender" },
    { "Skills": "Cinema 4D" },
    { "Skills": "Maya" },
    { "Skills": "ZBrush" },
    { "Skills": "Procreate" },
    { "Skills": "Substance Designer" },
    { "Skills": "Unreal Engine" },
    { "Skills": "Unity" },
    { "Skills": "Prototyping" },
    { "Skills": "Wireframing" },
    { "Skills": "User Research" },
    { "Skills": "Usability Testing" },
    { "Skills": "Accessibility Design" },
    { "Skills": "Information Architecture" },
    { "Skills": "CRM Systems" },
    { "Skills": "Analytics Tools" },
    { "Skills": "A/B Testing" },
    { "Skills": "Conversion Rate Optimization" },
    
    // Industry-Specific Skills
    { "Skills": "E-commerce Design" },
    { "Skills": "SaaS Design" },
    { "Skills": "Fintech Design" },
    { "Skills": "Healthcare Design" },
    { "Skills": "Educational Design" },
    { "Skills": "Gaming Industry Design" },
    { "Skills": "Sustainable Design Practices" },
    { "Skills": "Inclusive Design" },
    { "Skills": "Cross-Cultural Design" },
    { "Skills": "Design Systems" },
    { "Skills": "Design Thinking" },
    { "Skills": "Agile Methodology" },
    { "Skills": "Scrum" },
    { "Skills": "Kanban" },
    { "Skills": "Lean UX" },
    { "Skills": "Logo Design" },
    { "Skills": "Stationery Design" },
    { "Skills": "Fonts & Typography" },
    { "Skills": "Branding Services" },
    { "Skills": "Book Design" },
    { "Skills": "Packaging Design" },
    { "Skills": "Album Cover Design" },
    { "Skills": "Signage Design" },
    { "Skills": "Invitation Design" },
    { "Skills": "T-Shirt & Merchandise" },
    { "Skills": "Flyer & Brochure Design" },
    { "Skills": "Poster Design" },
    { "Skills": "Identity Design" },
    { "Skills": "Brand Guidelines" },
    { "Skills": "Website Design" },
    { "Skills": "App Design" },
    { "Skills": "UI/UX Design" },
    { "Skills": "Landing Page Design" },
    { "Skills": "Icon Design" },
    { "Skills": "Illustrations" },
    { "Skills": "Portraits" },
    { "Skills": "Comics & Character Design" },
    { "Skills": "Fashion Design" },
    { "Skills": "Pattern Design" },
    { "Skills": "Storyboards" },
    { "Skills": "Tattoo Design" },
    { "Skills": "NFT Art" },
    { "Skills": "3D Illustration" },
    { "Skills": "Children's Illustration" },
    { "Skills": "Social Media Design" },
    { "Skills": "Presentation Design" },
    { "Skills": "Infographic Design" },
    { "Skills": "Resume Design" },
    { "Skills": "Copywriting" },
    { "Skills": "Product Photography" },
    { "Skills": "Landscape Photography" },
    { "Skills": "Image Editing & Retouching" },
    { "Skills": "Portrait Photography" },
    { "Skills": "Architecture & Interior Design" },
    { "Skills": "Landscape Design" },
    { "Skills": "Industrial Design" },
    { "Skills": "Graphics for Streamers" },
    { "Skills": "Game Design" },
    { "Skills": "Creative Tool Coaching" },
    { "Skills": "Mentorship & Career Advice" },
    { "Skills": "Modeling Projects" },
    { "Skills": "Architecture Renderings" },
    { "Skills": "Music Composition & Production" },
    { "Skills": "Sound Design" },
    { "Skills": "Animated Gifs" },
    { "Skills": "Logo Animation" },
    { "Skills": "Motion Graphics" },
    { "Skills": "Video Production & Editing" },
    { "Skills": "Explainer Videos" },
    { "Skills": "Short Video Ads" },
    
    // Expanded Graphic Design Skills
    { "Skills": "Layout Design" },
    { "Skills": "Corporate Identity Design" },
    { "Skills": "Print Design" },
    { "Skills": "Catalog Design" },
    { "Skills": "Magazine Layout" },
    { "Skills": "Newspaper Design" },
    { "Skills": "Annual Report Design" },
    { "Skills": "Menu Design" },
    { "Skills": "Billboard Design" },
    { "Skills": "Trade Show Booth Design" },
    { "Skills": "Vehicle Wrap Design" },
    { "Skills": "Point of Purchase Display Design" },
    { "Skills": "Retail Graphics" },
    { "Skills": "CD/DVD Cover Design" },
    { "Skills": "Book Cover Design" },
    { "Skills": "Editorial Design" },
    { "Skills": "Publication Design" },
    { "Skills": "Booklet Design" },
    { "Skills": "Business Card Design" },
    { "Skills": "Letterhead Design" },
    { "Skills": "Envelope Design" },
    { "Skills": "Label Design" },
    { "Skills": "Hang Tag Design" },
    { "Skills": "Ticket Design" },
    { "Skills": "Certificate Design" },
    { "Skills": "Coupon Design" },
    { "Skills": "Tag Design" },
    { "Skills": "Calendar Design" },
    { "Skills": "Greeting Card Design" },
    { "Skills": "Postcard Design" },
    { "Skills": "Direct Mail Design" },
    { "Skills": "Stamp Design" },
    { "Skills": "Currency Design" },
    { "Skills": "Wayfinding Design" },
    { "Skills": "Information Design" },
    
    // Expanded Typography & Font Skills
    { "Skills": "Font Creation" },
    { "Skills": "Type Design" },
    { "Skills": "Custom Lettering" },
    { "Skills": "Typeface Design" },
    { "Skills": "Font Restoration" },
    { "Skills": "Typography Layout" },
    { "Skills": "Kinetic Typography" },
    { "Skills": "Variable Font Design" },
    { "Skills": "Multi-script Typography" },
    { "Skills": "Arabic Typography" },
    { "Skills": "Chinese Typography" },
    { "Skills": "Cyrillic Typography" },
    { "Skills": "Devanagari Typography" },
    { "Skills": "Hebrew Typography" },
    { "Skills": "Japanese Typography" },
    { "Skills": "Korean Typography" },
    { "Skills": "Thai Typography" },
    { "Skills": "Experimental Typography" },
    { "Skills": "Web Typography" },
    { "Skills": "Responsive Typography" },
    
    // Expanded Digital Design Skills
    { "Skills": "Responsive Web Design" },
    { "Skills": "Mobile Design" },
    { "Skills": "Tablet Design" },
    { "Skills": "Desktop Design" },
    { "Skills": "Web Application Design" },
    { "Skills": "SaaS Interface Design" },
    { "Skills": "Admin Dashboard Design" },
    { "Skills": "Browser Extension Design" },
    { "Skills": "E-learning Platform Design" },
    { "Skills": "E-commerce Website Design" },
    { "Skills": "Marketplace Design" },
    { "Skills": "Portfolio Website Design" },
    { "Skills": "Blog Design" },
    { "Skills": "News Website Design" },
    { "Skills": "Social Network Design" },
    { "Skills": "Dating App Design" },
    { "Skills": "Fitness App Design" },
    { "Skills": "Medical App Design" },
    { "Skills": "Finance App Design" },
    { "Skills": "Food Delivery App Design" },
    { "Skills": "Travel App Design" },
    { "Skills": "Weather App Design" },
    { "Skills": "Music App Design" },
    { "Skills": "Video Streaming App Design" },
    { "Skills": "Chat Interface Design" },
    { "Skills": "Voice User Interface Design" },
    { "Skills": "AR Interface Design" },
    { "Skills": "VR Interface Design" },
    { "Skills": "Wearable Interface Design" },
    { "Skills": "Smart Home Interface Design" },
    { "Skills": "Automotive UI Design" },
    { "Skills": "Kiosk Interface Design" },
    { "Skills": "ATM Interface Design" },
    { "Skills": "POS System Design" },
    { "Skills": "Interactive Installation Design" },
    { "Skills": "IoT Interface Design" },
    { "Skills": "Game UI Design" },
    { "Skills": "Game UX Design" },
    { "Skills": "Game Menu Design" },
    { "Skills": "Game HUD Design" },
    { "Skills": "Game Asset Design" },
    
    // Expanded UX Skills
    { "Skills": "User Research" },
    { "Skills": "User Interviews" },
    { "Skills": "Contextual Inquiry" },
    { "Skills": "Ethnographic Research" },
    { "Skills": "Survey Design" },
    { "Skills": "Card Sorting" },
    { "Skills": "Usability Testing" },
    { "Skills": "Remote Testing" },
    { "Skills": "Guerrilla Testing" },
    { "Skills": "A/B Testing" },
    { "Skills": "Multivariate Testing" },
    { "Skills": "Eye Tracking" },
    { "Skills": "Heatmap Analysis" },
    { "Skills": "Journey Mapping" },
    { "Skills": "Empathy Mapping" },
    { "Skills": "User Personas" },
    { "Skills": "Jobs-to-be-Done" },
    { "Skills": "User Scenarios" },
    { "Skills": "User Stories" },
    { "Skills": "Use Cases" },
    { "Skills": "Task Analysis" },
    { "Skills": "Information Architecture" },
    { "Skills": "Site Mapping" },
    { "Skills": "Content Strategy" },
    { "Skills": "Content Mapping" },
    { "Skills": "User Flows" },
    { "Skills": "Wireframing" },
    { "Skills": "Low-fidelity Prototyping" },
    { "Skills": "High-fidelity Prototyping" },
    { "Skills": "Interactive Prototyping" },
    { "Skills": "Paper Prototyping" },
    { "Skills": "Digital Prototyping" },
    { "Skills": "Microinteraction Design" },
    { "Skills": "Animation Prototyping" },
    { "Skills": "Accessibility Design" },
    { "Skills": "WCAG Compliance" },
    { "Skills": "Screen Reader Optimization" },
    { "Skills": "Cognitive Load Optimization" },
    { "Skills": "Mobile UX Design" },
    { "Skills": "Responsive UX Design" },
    { "Skills": "Cross-platform UX" },
    
    // Expanded Illustration & Art Skills
    { "Skills": "Digital Painting" },
    { "Skills": "Vector Illustration" },
    { "Skills": "Pixel Art" },
    { "Skills": "Concept Art" },
    { "Skills": "Environment Design" },
    { "Skills": "Background Illustration" },
    { "Skills": "Character Design" },
    { "Skills": "Creature Design" },
    { "Skills": "Fantasy Illustration" },
    { "Skills": "Sci-Fi Illustration" },
    { "Skills": "Children's Book Illustration" },
    { "Skills": "Editorial Illustration" },
    { "Skills": "Fashion Illustration" },
    { "Skills": "Medical Illustration" },
    { "Skills": "Scientific Illustration" },
    { "Skills": "Technical Illustration" },
    { "Skills": "Botanical Illustration" },
    { "Skills": "Food Illustration" },
    { "Skills": "Architectural Illustration" },
    { "Skills": "Product Illustration" },
    { "Skills": "Spot Illustration" },
    { "Skills": "Icon Illustration" },
    { "Skills": "Infographic Illustration" },
    { "Skills": "Map Illustration" },
    { "Skills": "Isometric Illustration" },
    { "Skills": "Flat Design Illustration" },
    { "Skills": "Line Art" },
    { "Skills": "Stippling" },
    { "Skills": "Cross-hatching" },
    { "Skills": "Watercolor Illustration" },
    { "Skills": "Gouache Illustration" },
    { "Skills": "Ink Illustration" },
    { "Skills": "Pencil Illustration" },
    { "Skills": "Charcoal Illustration" },
    { "Skills": "Pastel Illustration" },
    { "Skills": "Acrylic Illustration" },
    { "Skills": "Oil Painting" },
    { "Skills": "Mixed Media Illustration" },
    { "Skills": "Collage" },
    { "Skills": "Printmaking" },
    { "Skills": "Linocut" },
    { "Skills": "Woodcut" },
    { "Skills": "Screen Printing" },
    { "Skills": "Etching" },
    { "Skills": "Lithography" },
    { "Skills": "Block Printing" },
    { "Skills": "Risograph" },
    { "Skills": "Political Cartooning" },
    { "Skills": "Editorial Cartooning" },
    { "Skills": "Comic Book Art" },
    { "Skills": "Manga" },
    { "Skills": "Anime" },
    { "Skills": "Webtoon Creation" },
    { "Skills": "Storyboard Art" },
    { "Skills": "Concept Sketching" },
    
    // Expanded Photography & Retouching Skills
    { "Skills": "Studio Photography" },
    { "Skills": "Location Photography" },
    { "Skills": "Commercial Photography" },
    { "Skills": "Advertising Photography" },
    { "Skills": "Corporate Photography" },
    { "Skills": "Event Photography" },
    { "Skills": "Wedding Photography" },
    { "Skills": "Sports Photography" },
    { "Skills": "Wildlife Photography" },
    { "Skills": "Nature Photography" },
    { "Skills": "Macro Photography" },
    { "Skills": "Street Photography" },
    { "Skills": "Travel Photography" },
    { "Skills": "Architectural Photography" },
    { "Skills": "Interior Photography" },
    { "Skills": "Real Estate Photography" },
    { "Skills": "Food Photography" },
    { "Skills": "Product Photography" },
    { "Skills": "Fashion Photography" },
    { "Skills": "Portrait Photography" },
    { "Skills": "Headshot Photography" },
    { "Skills": "Fine Art Photography" },
    { "Skills": "Documentary Photography" },
    { "Skills": "Photojournalism" },
    { "Skills": "Concert Photography" },
    { "Skills": "Night Photography" },
    { "Skills": "Aerial Photography" },
    { "Skills": "Drone Photography" },
    { "Skills": "Underwater Photography" },
    { "Skills": "360° Photography" },
    { "Skills": "Time-lapse Photography" },
    { "Skills": "HDR Photography" },
    { "Skills": "Black & White Photography" },
    { "Skills": "Film Photography" },
    { "Skills": "Medium Format Photography" },
    { "Skills": "Large Format Photography" },
    { "Skills": "Polaroid Photography" },
    { "Skills": "Photo Retouching" },
    { "Skills": "Photo Color Correction" },
    { "Skills": "Photo Manipulation" },
    { "Skills": "Photo Compositing" },
    { "Skills": "Portrait Retouching" },
    { "Skills": "Beauty Retouching" },
    { "Skills": "Product Retouching" },
    { "Skills": "Real Estate Photo Editing" },
    { "Skills": "Food Photo Editing" },
    { "Skills": "Fashion Photo Editing" },
    { "Skills": "Photo Restoration" },
    { "Skills": "RAW Processing" },
    { "Skills": "Lightroom Editing" },
    { "Skills": "Photoshop Editing" },
    
    // Expanded 3D & Animation Skills
    { "Skills": "3D Modeling" },
    { "Skills": "Polygonal Modeling" },
    { "Skills": "NURBS Modeling" },
    { "Skills": "Digital Sculpting" },
    { "Skills": "Hard Surface Modeling" },
    { "Skills": "Organic Modeling" },
    { "Skills": "Character Modeling" },
    { "Skills": "Environment Modeling" },
    { "Skills": "Architectural Modeling" },
    { "Skills": "Product Modeling" },
    { "Skills": "Vehicle Modeling" },
    { "Skills": "Weapon Modeling" },
    { "Skills": "Prop Modeling" },
    { "Skills": "Set Modeling" },
    { "Skills": "Procedural Modeling" },
    { "Skills": "UV Mapping" },
    { "Skills": "UV Unwrapping" },
    { "Skills": "Texture Painting" },
    { "Skills": "PBR Texturing" },
    { "Skills": "Procedural Texturing" },
];

const LinkedInSkills = [
    // Leadership & Management
    { "Skills": "People Management" },
    { "Skills": "Team Leadership" },
    { "Skills": "Strategic Planning" },
    { "Skills": "Change Management" },
    { "Skills": "Organizational Development" },
    { "Skills": "Performance Management" },
    { "Skills": "Executive Leadership" },
    { "Skills": "Business Strategy" },
    { "Skills": "Coaching" },
    { "Skills": "Mentoring" },
    { "Skills": "Conflict Resolution" },
    { "Skills": "Decision Making" },
    { "Skills": "Cross-functional Team Leadership" },
    { "Skills": "Talent Management" },
    { "Skills": "Process Improvement" },
    
    // Business Skills
    { "Skills": "Project Management" },
    { "Skills": "Business Development" },
    { "Skills": "Strategic Partnerships" },
    { "Skills": "Negotiation" },
    { "Skills": "Client Relationship Management" },
    { "Skills": "Sales" },
    { "Skills": "Account Management" },
    { "Skills": "Budget Management" },
    { "Skills": "Financial Analysis" },
    { "Skills": "Risk Management" },
    { "Skills": "Business Analysis" },
    { "Skills": "Stakeholder Management" },
    { "Skills": "Operations Management" },
    { "Skills": "Supply Chain Management" },
    { "Skills": "Product Management" },
    { "Skills": "Customer Success" },
    { "Skills": "Public Speaking" },
    { "Skills": "Presentation Skills" },
    
    // Marketing & Communications
    { "Skills": "Digital Marketing" },
    { "Skills": "Content Marketing" },
    { "Skills": "Social Media Marketing" },
    { "Skills": "Search Engine Optimization (SEO)" },
    { "Skills": "Email Marketing" },
    { "Skills": "Influencer Marketing" },
    { "Skills": "Brand Management" },
    { "Skills": "Market Research" },
    { "Skills": "Public Relations" },
    { "Skills": "Advertising" },
    { "Skills": "Copywriting" },
    { "Skills": "Content Strategy" },
    { "Skills": "Growth Marketing" },
    { "Skills": "Marketing Automation" },
    { "Skills": "Google Analytics" },
    { "Skills": "Conversion Rate Optimization" },
    { "Skills": "Customer Acquisition" },
    { "Skills": "Campaign Management" },
    
    // Technical Skills
    { "Skills": "Programming" },
    { "Skills": "SQL" },
    { "Skills": "Python" },
    { "Skills": "Java" },
    { "Skills": "JavaScript" },
    { "Skills": "C++" },
    { "Skills": "C#" },
    { "Skills": "Ruby" },
    { "Skills": "PHP" },
    { "Skills": "Node.js" },
    { "Skills": "React" },
    { "Skills": "Angular" },
    { "Skills": "Vue.js" },
    { "Skills": "Machine Learning" },
    { "Skills": "Artificial Intelligence" },
    { "Skills": "Data Science" },
    { "Skills": "Data Analysis" },
    { "Skills": "Cloud Computing" },
    { "Skills": "AWS" },
    { "Skills": "Azure" },
    { "Skills": "Google Cloud" },
    { "Skills": "DevOps" },
    { "Skills": "Cybersecurity" },
    { "Skills": "Blockchain" },
    { "Skills": "Database Management" },
    { "Skills": "API Development" },
    { "Skills": "Software Testing" },
    { "Skills": "Mobile Development" },
    
    // Data & Analytics
    { "Skills": "Data Visualization" },
    { "Skills": "Statistical Analysis" },
    { "Skills": "Business Intelligence" },
    { "Skills": "Power BI" },
    { "Skills": "Tableau" },
    { "Skills": "Looker" },
    { "Skills": "Excel" },
    { "Skills": "R" },
    { "Skills": "SPSS" },
    { "Skills": "SAS" },
    { "Skills": "Big Data" },
    { "Skills": "Data Modeling" },
    { "Skills": "ETL" },
    { "Skills": "Data Warehousing" },
    { "Skills": "Predictive Analytics" },
    { "Skills": "A/B Testing" },
    
    // Soft Skills
    { "Skills": "Communication" },
    { "Skills": "Teamwork" },
    { "Skills": "Problem Solving" },
    { "Skills": "Critical Thinking" },
    { "Skills": "Adaptability" },
    { "Skills": "Time Management" },
    { "Skills": "Creativity" },
    { "Skills": "Emotional Intelligence" },
    { "Skills": "Active Listening" },
    { "Skills": "Attention to Detail" },
    { "Skills": "Resilience" },
    { "Skills": "Work Ethic" },
    { "Skills": "Self-motivation" },
    { "Skills": "Collaboration" },
    { "Skills": "Cultural Awareness" },
    { "Skills": "Accountability" },
    { "Skills": "Interpersonal Skills" },
    { "Skills": "Learning Agility" },
    
    // Financial Skills
    { "Skills": "Financial Planning" },
    { "Skills": "Accounting" },
    { "Skills": "Budgeting" },
    { "Skills": "Financial Reporting" },
    { "Skills": "Financial Modeling" },
    { "Skills": "Investment Analysis" },
    { "Skills": "Forecasting" },
    { "Skills": "Tax Planning" },
    { "Skills": "Auditing" },
    { "Skills": "Cost Analysis" },
    { "Skills": "Mergers & Acquisitions" },
    { "Skills": "Venture Capital" },
    { "Skills": "Private Equity" },
    { "Skills": "Corporate Finance" },
    
    // Human Resources
    { "Skills": "Recruiting" },
    { "Skills": "Employee Relations" },
    { "Skills": "Benefits Administration" },
    { "Skills": "HRIS Systems" },
    { "Skills": "Onboarding" },
    { "Skills": "Diversity & Inclusion" },
    { "Skills": "Training & Development" },
    { "Skills": "Compensation Planning" },
    { "Skills": "Succession Planning" },
    { "Skills": "Performance Reviews" },
    { "Skills": "HR Compliance" },
    { "Skills": "Workforce Planning" },
    { "Skills": "Employee Engagement" },
    { "Skills": "Labor Relations" },
    
    // Industry-Specific
    { "Skills": "Healthcare Management" },
    { "Skills": "Pharmaceutical" },
    { "Skills": "Banking" },
    { "Skills": "Insurance" },
    { "Skills": "Real Estate" },
    { "Skills": "Retail Management" },
    { "Skills": "Hospitality" },
    { "Skills": "Manufacturing" },
    { "Skills": "Logistics" },
    { "Skills": "E-commerce" },
    { "Skills": "Telecommunications" },
    { "Skills": "Construction Management" },
    { "Skills": "Automotive" },
    { "Skills": "Energy & Utilities" },
    { "Skills": "Aerospace" },
    { "Skills": "Legal Services" },
    { "Skills": "Education Management" },
    { "Skills": "Nonprofit Management" },
    
    // Software & Tools
    { "Skills": "Microsoft Office" },
    { "Skills": "Google Workspace" },
    { "Skills": "Salesforce" },
    { "Skills": "HubSpot" },
    { "Skills": "Jira" },
    { "Skills": "Confluence" },
    { "Skills": "Asana" },
    { "Skills": "Trello" },
    { "Skills": "Slack" },
    { "Skills": "Zoom" },
    { "Skills": "Microsoft Teams" },
    { "Skills": "SAP" },
    { "Skills": "Oracle" },
    { "Skills": "Workday" },
    { "Skills": "QuickBooks" },
    { "Skills": "Adobe Creative Suite" },
    { "Skills": "CRM Systems" },
    { "Skills": "ERP Systems" },
    
    // Project Management Methodologies
    { "Skills": "Agile" },
    { "Skills": "Scrum" },
    { "Skills": "Kanban" },
    { "Skills": "Waterfall" },
    { "Skills": "Lean" },
    { "Skills": "Six Sigma" },
    { "Skills": "PMP" },
    { "Skills": "PRINCE2" },
    { "Skills": "ITIL" },
    { "Skills": "Sprint Planning" },
    { "Skills": "Backlog Management" },
    { "Skills": "Continuous Integration" },
    { "Skills": "Continuous Deployment" },
    
    // Languages
    { "Skills": "English" },
    { "Skills": "Spanish" },
    { "Skills": "Chinese" },
    { "Skills": "French" },
    { "Skills": "German" },
    { "Skills": "Japanese" },
    { "Skills": "Portuguese" },
    { "Skills": "Russian" },
    { "Skills": "Arabic" },
    { "Skills": "Hindi" },
    { "Skills": "Italian" },
    { "Skills": "Korean" },
    
    // Certifications (as skills)
    { "Skills": "PMP Certification" },
    { "Skills": "Lean Six Sigma" },
    { "Skills": "Scrum Master" },
    { "Skills": "CISSP" },
    { "Skills": "CPA" },
    { "Skills": "CFA" },
    { "Skills": "AWS Certified" },
    { "Skills": "Google Certified" },
    { "Skills": "Microsoft Certified" },
    { "Skills": "Salesforce Certified" },
    { "Skills": "CompTIA" },
    { "Skills": "SHRM-CP" },
    { "Skills": "PHR" },
];
/**
 * Inserts scraped data into a specified Supabase table.
 *
 * @async
 * @function addDataToSupabase
 * @param {Array<Object>} scrapedData - An array of objects containing the data to be inserted.
 * @param {string} [tableName='skills_data_table'] - The name of the table where data should be inserted (default is 'skills_data_table').
 * @returns {Promise<boolean>} - Returns `true` if insertion is successful, otherwise `false`.
 */
async function addDataToSupabase(scrapedData, tableName = 'skills_data_table') {
    try {
      console.log(`Inserting ${scrapedData.length} records into ${tableName}...`);
       
      const { data, error } = await supabase
        .from(tableName)
        .insert(scrapedData);
       
      if (error) {
        console.error(`Error inserting data into ${tableName}:`, error);
        return false;
      }
       
      console.log(`Data inserted successfully into ${tableName}:`, data);
      return true;
    } catch (err) {
      console.error(`Exception when inserting data into ${tableName}:`, err);
      return false;
    }
  }
  
  /**
   * Transforms the `Skills` array into the expected format and inserts it into Supabase.
   *
   * @async
   * @function main
   * @returns {Promise<void>} - Does not return a value, but logs the insertion status.
   */
  async function main() {
    try {
      // Transform the Skills array into the format expected by the database
      const formattedSkills = LinkedInSkills.map(skill => {
        return { skill: skill.Skills }; 
      });
  
      // Insert all skills in a bulk operation
      const result = await addDataToSupabase(formattedSkills);
      
      if (result) {
        console.log(`Added ${formattedSkills.length} skills to skills_data_table in Supabase`);
      }
    } catch (error) {
      console.log("Error occurred adding data to Supabase", error);
    }
  }
  
main();  
